import type { DemoTheme, DemoInfo } from "./types";

// Restaurant Theme
export const restaurantTheme: DemoTheme = {
  demoId: "restaurant",
  name: "Restaurant",
  description: "Fine dining and culinary experiences",
  defaultScheme: "warm",
  schemes: [
    {
      id: "warm",
      name: "Warm & Cozy",
      colors: {
        primary: "#C41E3A",
        primaryForeground: "#FFFFFF",
        secondary: "#2C1810",
        secondaryForeground: "#FFFFFF",
        accent: "#D4A574",
        accentForeground: "#1A1A1A",
        background: "#FFF8F0",
        foreground: "#1A1A1A",
        muted: "#F5EDE4",
        mutedForeground: "#6B5C4C",
        card: "#FFFFFF",
        cardForeground: "#1A1A1A",
        border: "#E8DDD0",
        ring: "#C41E3A",
      },
    },
    {
      id: "modern",
      name: "Modern Minimal",
      colors: {
        primary: "#1A1A1A",
        primaryForeground: "#FFFFFF",
        secondary: "#F5F5F5",
        secondaryForeground: "#1A1A1A",
        accent: "#4A7C59",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1A1A1A",
        muted: "#F5F5F5",
        mutedForeground: "#6B6B6B",
        card: "#FFFFFF",
        cardForeground: "#1A1A1A",
        border: "#E5E5E5",
        ring: "#1A1A1A",
      },
    },
    {
      id: "dark",
      name: "Evening Elegance",
      colors: {
        primary: "#D4AF37",
        primaryForeground: "#0D0D0D",
        secondary: "#1A1A1A",
        secondaryForeground: "#F5F5F5",
        accent: "#722F37",
        accentForeground: "#FFFFFF",
        background: "#0D0D0D",
        foreground: "#F5F5F5",
        muted: "#1A1A1A",
        mutedForeground: "#A0A0A0",
        card: "#141414",
        cardForeground: "#F5F5F5",
        border: "#2A2A2A",
        ring: "#D4AF37",
      },
    },
  ],
};

// Portfolio Theme
export const portfolioTheme: DemoTheme = {
  demoId: "portfolio",
  name: "Portfolio",
  description: "Creative professional portfolio",
  defaultScheme: "minimal",
  schemes: [
    {
      id: "minimal",
      name: "Minimal",
      colors: {
        primary: "#000000",
        primaryForeground: "#FFFFFF",
        secondary: "#F8F8F8",
        secondaryForeground: "#000000",
        accent: "#0066FF",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#000000",
        muted: "#F5F5F5",
        mutedForeground: "#666666",
        card: "#FFFFFF",
        cardForeground: "#000000",
        border: "#EBEBEB",
        ring: "#0066FF",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#FFFFFF",
        primaryForeground: "#000000",
        secondary: "#1A1A1A",
        secondaryForeground: "#FFFFFF",
        accent: "#00D4FF",
        accentForeground: "#000000",
        background: "#0A0A0A",
        foreground: "#FFFFFF",
        muted: "#1A1A1A",
        mutedForeground: "#999999",
        card: "#111111",
        cardForeground: "#FFFFFF",
        border: "#2A2A2A",
        ring: "#00D4FF",
      },
    },
    {
      id: "creative",
      name: "Creative",
      colors: {
        primary: "#FF3366",
        primaryForeground: "#FFFFFF",
        secondary: "#FFF0F3",
        secondaryForeground: "#1A1A1A",
        accent: "#9333EA",
        accentForeground: "#FFFFFF",
        background: "#FFFBFC",
        foreground: "#1A1A1A",
        muted: "#FFF0F3",
        mutedForeground: "#666666",
        card: "#FFFFFF",
        cardForeground: "#1A1A1A",
        border: "#FFE0E6",
        ring: "#FF3366",
      },
    },
  ],
};

// SaaS Theme
export const saasTheme: DemoTheme = {
  demoId: "saas",
  name: "SaaS",
  description: "Software as a Service landing page",
  defaultScheme: "tech",
  schemes: [
    {
      id: "tech",
      name: "Tech Blue",
      colors: {
        primary: "#2563EB",
        primaryForeground: "#FFFFFF",
        secondary: "#EFF6FF",
        secondaryForeground: "#1E40AF",
        accent: "#06B6D4",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#64748B",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        border: "#E2E8F0",
        ring: "#2563EB",
      },
    },
    {
      id: "purple",
      name: "Purple Gradient",
      colors: {
        primary: "#7C3AED",
        primaryForeground: "#FFFFFF",
        secondary: "#F3E8FF",
        secondaryForeground: "#5B21B6",
        accent: "#EC4899",
        accentForeground: "#FFFFFF",
        background: "#FAFAFA",
        foreground: "#18181B",
        muted: "#F4F4F5",
        mutedForeground: "#71717A",
        card: "#FFFFFF",
        cardForeground: "#18181B",
        border: "#E4E4E7",
        ring: "#7C3AED",
      },
    },
    {
      id: "dark",
      name: "Dark Tech",
      colors: {
        primary: "#3B82F6",
        primaryForeground: "#FFFFFF",
        secondary: "#1E293B",
        secondaryForeground: "#E2E8F0",
        accent: "#22D3EE",
        accentForeground: "#0F172A",
        background: "#0F172A",
        foreground: "#F8FAFC",
        muted: "#1E293B",
        mutedForeground: "#94A3B8",
        card: "#1E293B",
        cardForeground: "#F8FAFC",
        border: "#334155",
        ring: "#3B82F6",
      },
    },
  ],
};

// All demo information for the showcase
export const demos: DemoInfo[] = [
  {
    id: "restaurant",
    name: "Restaurant",
    description: "Elegant dining experience with menu showcases and reservations",
    category: "Hospitality",
    href: "/demos/restaurant",
  },
  {
    id: "handyman",
    name: "Handyman",
    description: "Professional home services with booking and service areas",
    category: "Services",
    href: "/demos/handyman",
  },
  {
    id: "portfolio",
    name: "Portfolio",
    description: "Creative professional portfolio with project showcases",
    category: "Creative",
    href: "/demos/portfolio",
  },
  {
    id: "saas",
    name: "SaaS Landing",
    description: "Modern software product landing with pricing and features",
    category: "Technology",
    href: "/demos/saas",
  },
  {
    id: "ecommerce",
    name: "E-commerce",
    description: "Online store with product catalog and shopping experience",
    category: "Retail",
    href: "/demos/ecommerce",
  },
  {
    id: "agency",
    name: "Digital Agency",
    description: "Creative agency showcasing services and case studies",
    category: "Creative",
    href: "/demos/agency",
  },
  {
    id: "blog",
    name: "Blog",
    description: "Modern blog with articles, categories, and reading experience",
    category: "Content",
    href: "/demos/blog",
  },
  {
    id: "real-estate",
    name: "Real Estate",
    description: "Property listings with search, maps, and virtual tours",
    category: "Real Estate",
    href: "/demos/real-estate",
  },
  {
    id: "gym",
    name: "Gym & Fitness",
    description: "Fitness center with classes, trainers, and memberships",
    category: "Health",
    href: "/demos/gym",
  },
  {
    id: "law-firm",
    name: "Law Firm",
    description: "Professional legal services with practice areas and attorneys",
    category: "Professional",
    href: "/demos/law-firm",
  },
  {
    id: "medical",
    name: "Medical Clinic",
    description: "Healthcare facility with doctors, services, and appointments",
    category: "Health",
    href: "/demos/medical",
  },
  {
    id: "photography",
    name: "Photography",
    description: "Visual portfolio with galleries and booking options",
    category: "Creative",
    href: "/demos/photography",
  },
];

// Export all themes
export const themes: Record<string, DemoTheme> = {
  restaurant: restaurantTheme,
  portfolio: portfolioTheme,
  saas: saasTheme,
  // More themes will be added as we build each demo
};

export * from "./types";
