import type { DemoTheme, DemoInfo } from "./types";

// Restaurant Theme
export const restaurantTheme: DemoTheme = {
  demoId: "restaurant",
  name: "Restaurant",
  description: "Fine dining and culinary experiences",
  defaultScheme: "warm",
  schemes: [
    {
      id: "warm",
      name: "Warm & Cozy",
      colors: {
        primary: "#C41E3A",
        primaryForeground: "#FFFFFF",
        secondary: "#2C1810",
        secondaryForeground: "#FFFFFF",
        accent: "#D4A574",
        accentForeground: "#1A1A1A",
        background: "#FFF8F0",
        foreground: "#1A1A1A",
        muted: "#F5EDE4",
        mutedForeground: "#6B5C4C",
        card: "#FFFFFF",
        cardForeground: "#1A1A1A",
        border: "#E8DDD0",
        ring: "#C41E3A",
      },
    },
    {
      id: "modern",
      name: "Modern Minimal",
      colors: {
        primary: "#1A1A1A",
        primaryForeground: "#FFFFFF",
        secondary: "#F5F5F5",
        secondaryForeground: "#1A1A1A",
        accent: "#4A7C59",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1A1A1A",
        muted: "#F5F5F5",
        mutedForeground: "#6B6B6B",
        card: "#FFFFFF",
        cardForeground: "#1A1A1A",
        border: "#E5E5E5",
        ring: "#1A1A1A",
      },
    },
    {
      id: "dark",
      name: "Evening Elegance",
      colors: {
        primary: "#D4AF37",
        primaryForeground: "#0D0D0D",
        secondary: "#1A1A1A",
        secondaryForeground: "#F5F5F5",
        accent: "#722F37",
        accentForeground: "#FFFFFF",
        background: "#0D0D0D",
        foreground: "#F5F5F5",
        muted: "#1A1A1A",
        mutedForeground: "#A0A0A0",
        card: "#141414",
        cardForeground: "#F5F5F5",
        border: "#2A2A2A",
        ring: "#D4AF37",
      },
    },
  ],
};

// Portfolio Theme
export const portfolioTheme: DemoTheme = {
  demoId: "portfolio",
  name: "Portfolio",
  description: "Creative professional portfolio",
  defaultScheme: "minimal",
  schemes: [
    {
      id: "minimal",
      name: "Minimal",
      colors: {
        primary: "#000000",
        primaryForeground: "#FFFFFF",
        secondary: "#F8F8F8",
        secondaryForeground: "#000000",
        accent: "#0066FF",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#000000",
        muted: "#F5F5F5",
        mutedForeground: "#666666",
        card: "#FFFFFF",
        cardForeground: "#000000",
        border: "#EBEBEB",
        ring: "#0066FF",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#FFFFFF",
        primaryForeground: "#000000",
        secondary: "#1A1A1A",
        secondaryForeground: "#FFFFFF",
        accent: "#00D4FF",
        accentForeground: "#000000",
        background: "#0A0A0A",
        foreground: "#FFFFFF",
        muted: "#1A1A1A",
        mutedForeground: "#999999",
        card: "#111111",
        cardForeground: "#FFFFFF",
        border: "#2A2A2A",
        ring: "#00D4FF",
      },
    },
    {
      id: "creative",
      name: "Creative",
      colors: {
        primary: "#FF3366",
        primaryForeground: "#FFFFFF",
        secondary: "#FFF0F3",
        secondaryForeground: "#1A1A1A",
        accent: "#9333EA",
        accentForeground: "#FFFFFF",
        background: "#FFFBFC",
        foreground: "#1A1A1A",
        muted: "#FFF0F3",
        mutedForeground: "#666666",
        card: "#FFFFFF",
        cardForeground: "#1A1A1A",
        border: "#FFE0E6",
        ring: "#FF3366",
      },
    },
  ],
};

// SaaS Theme
export const saasTheme: DemoTheme = {
  demoId: "saas",
  name: "SaaS",
  description: "Software as a Service landing page",
  defaultScheme: "tech",
  schemes: [
    {
      id: "tech",
      name: "Tech Blue",
      colors: {
        primary: "#2563EB",
        primaryForeground: "#FFFFFF",
        secondary: "#EFF6FF",
        secondaryForeground: "#1E40AF",
        accent: "#06B6D4",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#0F172A",
        muted: "#F1F5F9",
        mutedForeground: "#64748B",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        border: "#E2E8F0",
        ring: "#2563EB",
      },
    },
    {
      id: "purple",
      name: "Purple Gradient",
      colors: {
        primary: "#7C3AED",
        primaryForeground: "#FFFFFF",
        secondary: "#F3E8FF",
        secondaryForeground: "#5B21B6",
        accent: "#EC4899",
        accentForeground: "#FFFFFF",
        background: "#FAFAFA",
        foreground: "#18181B",
        muted: "#F4F4F5",
        mutedForeground: "#71717A",
        card: "#FFFFFF",
        cardForeground: "#18181B",
        border: "#E4E4E7",
        ring: "#7C3AED",
      },
    },
    {
      id: "dark",
      name: "Dark Tech",
      colors: {
        primary: "#3B82F6",
        primaryForeground: "#FFFFFF",
        secondary: "#1E293B",
        secondaryForeground: "#E2E8F0",
        accent: "#22D3EE",
        accentForeground: "#0F172A",
        background: "#0F172A",
        foreground: "#F8FAFC",
        muted: "#1E293B",
        mutedForeground: "#94A3B8",
        card: "#1E293B",
        cardForeground: "#F8FAFC",
        border: "#334155",
        ring: "#3B82F6",
      },
    },
  ],
};

// All demo information for the showcase
export const demos: DemoInfo[] = [
  {
    id: "restaurant",
    name: "Restaurant",
    description: "Elegant dining experience with menu showcases and reservations",
    category: "Hospitality",
    href: "/demos/restaurant",
  },
  {
    id: "handyman",
    name: "Handyman",
    description: "Professional home services with booking and service areas",
    category: "Services",
    href: "/demos/handyman",
  },
  {
    id: "portfolio",
    name: "Portfolio",
    description: "Creative professional portfolio with project showcases",
    category: "Creative",
    href: "/demos/portfolio",
  },
  {
    id: "saas",
    name: "SaaS Landing",
    description: "Modern software product landing with pricing and features",
    category: "Technology",
    href: "/demos/saas",
  },
  {
    id: "ecommerce",
    name: "E-commerce",
    description: "Online store with product catalog and shopping experience",
    category: "Retail",
    href: "/demos/ecommerce",
  },
  {
    id: "agency",
    name: "Digital Agency",
    description: "Creative agency showcasing services and case studies",
    category: "Creative",
    href: "/demos/agency",
  },
  {
    id: "blog",
    name: "Blog",
    description: "Modern blog with articles, categories, and reading experience",
    category: "Content",
    href: "/demos/blog",
  },
  {
    id: "real-estate",
    name: "Real Estate",
    description: "Property listings with search, maps, and virtual tours",
    category: "Real Estate",
    href: "/demos/real-estate",
  },
  {
    id: "gym",
    name: "Gym & Fitness",
    description: "Fitness center with classes, trainers, and memberships",
    category: "Health",
    href: "/demos/gym",
  },
  {
    id: "law-firm",
    name: "Law Firm",
    description: "Professional legal services with practice areas and attorneys",
    category: "Professional",
    href: "/demos/law-firm",
  },
  {
    id: "medical",
    name: "Medical Clinic",
    description: "Healthcare facility with doctors, services, and appointments",
    category: "Health",
    href: "/demos/medical",
  },
  {
    id: "photography",
    name: "Photography",
    description: "Visual portfolio with galleries and booking options",
    category: "Creative",
    href: "/demos/photography",
  },
];

// Handyman Theme
export const handymanTheme: DemoTheme = {
  demoId: "handyman",
  name: "Handyman",
  description: "Professional home services",
  defaultScheme: "professional",
  schemes: [
    {
      id: "professional",
      name: "Professional",
      colors: {
        primary: "#F59E0B",
        primaryForeground: "#000000",
        secondary: "#1E3A5F",
        secondaryForeground: "#FFFFFF",
        accent: "#10B981",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1F2937",
        muted: "#F3F4F6",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#1F2937",
        border: "#E5E7EB",
        ring: "#F59E0B",
      },
    },
    {
      id: "industrial",
      name: "Industrial",
      colors: {
        primary: "#EF4444",
        primaryForeground: "#FFFFFF",
        secondary: "#374151",
        secondaryForeground: "#FFFFFF",
        accent: "#FCD34D",
        accentForeground: "#000000",
        background: "#F9FAFB",
        foreground: "#111827",
        muted: "#E5E7EB",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#111827",
        border: "#D1D5DB",
        ring: "#EF4444",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#FBBF24",
        primaryForeground: "#000000",
        secondary: "#374151",
        secondaryForeground: "#F9FAFB",
        accent: "#34D399",
        accentForeground: "#000000",
        background: "#111827",
        foreground: "#F9FAFB",
        muted: "#1F2937",
        mutedForeground: "#9CA3AF",
        card: "#1F2937",
        cardForeground: "#F9FAFB",
        border: "#374151",
        ring: "#FBBF24",
      },
    },
  ],
};

// E-commerce Theme
export const ecommerceTheme: DemoTheme = {
  demoId: "ecommerce",
  name: "E-commerce",
  description: "Online shopping experience",
  defaultScheme: "modern",
  schemes: [
    {
      id: "modern",
      name: "Modern Shop",
      colors: {
        primary: "#000000",
        primaryForeground: "#FFFFFF",
        secondary: "#F5F5F5",
        secondaryForeground: "#000000",
        accent: "#FF6B6B",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#171717",
        muted: "#FAFAFA",
        mutedForeground: "#737373",
        card: "#FFFFFF",
        cardForeground: "#171717",
        border: "#E5E5E5",
        ring: "#000000",
      },
    },
    {
      id: "luxury",
      name: "Luxury",
      colors: {
        primary: "#B8860B",
        primaryForeground: "#FFFFFF",
        secondary: "#1A1A1A",
        secondaryForeground: "#FFFFFF",
        accent: "#CD853F",
        accentForeground: "#FFFFFF",
        background: "#FFFEF7",
        foreground: "#1A1A1A",
        muted: "#F5F3E8",
        mutedForeground: "#666666",
        card: "#FFFFFF",
        cardForeground: "#1A1A1A",
        border: "#E8E4D4",
        ring: "#B8860B",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#FFFFFF",
        primaryForeground: "#000000",
        secondary: "#262626",
        secondaryForeground: "#FFFFFF",
        accent: "#F472B6",
        accentForeground: "#000000",
        background: "#0A0A0A",
        foreground: "#FAFAFA",
        muted: "#171717",
        mutedForeground: "#A3A3A3",
        card: "#171717",
        cardForeground: "#FAFAFA",
        border: "#262626",
        ring: "#FFFFFF",
      },
    },
  ],
};

// Agency Theme
export const agencyTheme: DemoTheme = {
  demoId: "agency",
  name: "Digital Agency",
  description: "Creative agency showcase",
  defaultScheme: "bold",
  schemes: [
    {
      id: "bold",
      name: "Bold Creative",
      colors: {
        primary: "#FF0066",
        primaryForeground: "#FFFFFF",
        secondary: "#1A1A1A",
        secondaryForeground: "#FFFFFF",
        accent: "#00FFAA",
        accentForeground: "#000000",
        background: "#FFFFFF",
        foreground: "#0A0A0A",
        muted: "#F5F5F5",
        mutedForeground: "#666666",
        card: "#FFFFFF",
        cardForeground: "#0A0A0A",
        border: "#EBEBEB",
        ring: "#FF0066",
      },
    },
    {
      id: "minimal",
      name: "Minimal",
      colors: {
        primary: "#0A0A0A",
        primaryForeground: "#FFFFFF",
        secondary: "#F8F8F8",
        secondaryForeground: "#0A0A0A",
        accent: "#3B82F6",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#0A0A0A",
        muted: "#F5F5F5",
        mutedForeground: "#737373",
        card: "#FFFFFF",
        cardForeground: "#0A0A0A",
        border: "#E5E5E5",
        ring: "#0A0A0A",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#00FF88",
        primaryForeground: "#000000",
        secondary: "#1A1A1A",
        secondaryForeground: "#FFFFFF",
        accent: "#FF6B9D",
        accentForeground: "#000000",
        background: "#0A0A0A",
        foreground: "#FFFFFF",
        muted: "#1A1A1A",
        mutedForeground: "#999999",
        card: "#141414",
        cardForeground: "#FFFFFF",
        border: "#2A2A2A",
        ring: "#00FF88",
      },
    },
  ],
};

// Blog Theme
export const blogTheme: DemoTheme = {
  demoId: "blog",
  name: "Blog",
  description: "Modern blog experience",
  defaultScheme: "clean",
  schemes: [
    {
      id: "clean",
      name: "Clean Editorial",
      colors: {
        primary: "#0F172A",
        primaryForeground: "#FFFFFF",
        secondary: "#F8FAFC",
        secondaryForeground: "#0F172A",
        accent: "#DC2626",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1E293B",
        muted: "#F1F5F9",
        mutedForeground: "#64748B",
        card: "#FFFFFF",
        cardForeground: "#1E293B",
        border: "#E2E8F0",
        ring: "#0F172A",
      },
    },
    {
      id: "warm",
      name: "Warm & Cozy",
      colors: {
        primary: "#92400E",
        primaryForeground: "#FFFFFF",
        secondary: "#FEF3C7",
        secondaryForeground: "#78350F",
        accent: "#059669",
        accentForeground: "#FFFFFF",
        background: "#FFFBEB",
        foreground: "#1C1917",
        muted: "#FEF3C7",
        mutedForeground: "#78716C",
        card: "#FFFFFF",
        cardForeground: "#1C1917",
        border: "#FDE68A",
        ring: "#92400E",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#F8FAFC",
        primaryForeground: "#0F172A",
        secondary: "#1E293B",
        secondaryForeground: "#F8FAFC",
        accent: "#FB923C",
        accentForeground: "#000000",
        background: "#0F172A",
        foreground: "#F1F5F9",
        muted: "#1E293B",
        mutedForeground: "#94A3B8",
        card: "#1E293B",
        cardForeground: "#F1F5F9",
        border: "#334155",
        ring: "#F8FAFC",
      },
    },
  ],
};

// Real Estate Theme
export const realEstateTheme: DemoTheme = {
  demoId: "real-estate",
  name: "Real Estate",
  description: "Property listings and search",
  defaultScheme: "professional",
  schemes: [
    {
      id: "professional",
      name: "Professional",
      colors: {
        primary: "#1E40AF",
        primaryForeground: "#FFFFFF",
        secondary: "#EFF6FF",
        secondaryForeground: "#1E40AF",
        accent: "#059669",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1F2937",
        muted: "#F3F4F6",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#1F2937",
        border: "#E5E7EB",
        ring: "#1E40AF",
      },
    },
    {
      id: "luxury",
      name: "Luxury Estates",
      colors: {
        primary: "#78350F",
        primaryForeground: "#FFFFFF",
        secondary: "#FEF3C7",
        secondaryForeground: "#78350F",
        accent: "#0D9488",
        accentForeground: "#FFFFFF",
        background: "#FFFBEB",
        foreground: "#1C1917",
        muted: "#F5F5F4",
        mutedForeground: "#78716C",
        card: "#FFFFFF",
        cardForeground: "#1C1917",
        border: "#E7E5E4",
        ring: "#78350F",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#60A5FA",
        primaryForeground: "#000000",
        secondary: "#1E3A5F",
        secondaryForeground: "#E0F2FE",
        accent: "#34D399",
        accentForeground: "#000000",
        background: "#0C1222",
        foreground: "#F1F5F9",
        muted: "#1E293B",
        mutedForeground: "#94A3B8",
        card: "#162032",
        cardForeground: "#F1F5F9",
        border: "#2D4356",
        ring: "#60A5FA",
      },
    },
  ],
};

// Gym Theme
export const gymTheme: DemoTheme = {
  demoId: "gym",
  name: "Gym & Fitness",
  description: "Fitness center and training",
  defaultScheme: "energy",
  schemes: [
    {
      id: "energy",
      name: "High Energy",
      colors: {
        primary: "#EF4444",
        primaryForeground: "#FFFFFF",
        secondary: "#1F2937",
        secondaryForeground: "#FFFFFF",
        accent: "#22C55E",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#111827",
        muted: "#F3F4F6",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#111827",
        border: "#E5E7EB",
        ring: "#EF4444",
      },
    },
    {
      id: "power",
      name: "Power Dark",
      colors: {
        primary: "#F97316",
        primaryForeground: "#000000",
        secondary: "#18181B",
        secondaryForeground: "#FAFAFA",
        accent: "#A855F7",
        accentForeground: "#FFFFFF",
        background: "#09090B",
        foreground: "#FAFAFA",
        muted: "#18181B",
        mutedForeground: "#A1A1AA",
        card: "#18181B",
        cardForeground: "#FAFAFA",
        border: "#27272A",
        ring: "#F97316",
      },
    },
    {
      id: "zen",
      name: "Zen Wellness",
      colors: {
        primary: "#0D9488",
        primaryForeground: "#FFFFFF",
        secondary: "#F0FDFA",
        secondaryForeground: "#134E4A",
        accent: "#F59E0B",
        accentForeground: "#000000",
        background: "#FFFFFF",
        foreground: "#1C1917",
        muted: "#F5F5F4",
        mutedForeground: "#78716C",
        card: "#FFFFFF",
        cardForeground: "#1C1917",
        border: "#E7E5E4",
        ring: "#0D9488",
      },
    },
  ],
};

// Law Firm Theme
export const lawFirmTheme: DemoTheme = {
  demoId: "law-firm",
  name: "Law Firm",
  description: "Professional legal services",
  defaultScheme: "classic",
  schemes: [
    {
      id: "classic",
      name: "Classic Professional",
      colors: {
        primary: "#1E3A5F",
        primaryForeground: "#FFFFFF",
        secondary: "#F8FAFC",
        secondaryForeground: "#1E3A5F",
        accent: "#B8860B",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1F2937",
        muted: "#F3F4F6",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#1F2937",
        border: "#E5E7EB",
        ring: "#1E3A5F",
      },
    },
    {
      id: "modern",
      name: "Modern Firm",
      colors: {
        primary: "#0F172A",
        primaryForeground: "#FFFFFF",
        secondary: "#F1F5F9",
        secondaryForeground: "#0F172A",
        accent: "#0EA5E9",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#0F172A",
        muted: "#F8FAFC",
        mutedForeground: "#64748B",
        card: "#FFFFFF",
        cardForeground: "#0F172A",
        border: "#E2E8F0",
        ring: "#0F172A",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#E2E8F0",
        primaryForeground: "#0F172A",
        secondary: "#1E293B",
        secondaryForeground: "#E2E8F0",
        accent: "#D4AF37",
        accentForeground: "#000000",
        background: "#0F172A",
        foreground: "#F1F5F9",
        muted: "#1E293B",
        mutedForeground: "#94A3B8",
        card: "#1E293B",
        cardForeground: "#F1F5F9",
        border: "#334155",
        ring: "#E2E8F0",
      },
    },
  ],
};

// Medical Theme
export const medicalTheme: DemoTheme = {
  demoId: "medical",
  name: "Medical Clinic",
  description: "Healthcare and medical services",
  defaultScheme: "clean",
  schemes: [
    {
      id: "clean",
      name: "Clean Medical",
      colors: {
        primary: "#0891B2",
        primaryForeground: "#FFFFFF",
        secondary: "#ECFEFF",
        secondaryForeground: "#0891B2",
        accent: "#059669",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#1F2937",
        muted: "#F3F4F6",
        mutedForeground: "#6B7280",
        card: "#FFFFFF",
        cardForeground: "#1F2937",
        border: "#E5E7EB",
        ring: "#0891B2",
      },
    },
    {
      id: "warm",
      name: "Warm Care",
      colors: {
        primary: "#0D9488",
        primaryForeground: "#FFFFFF",
        secondary: "#F0FDFA",
        secondaryForeground: "#134E4A",
        accent: "#F97316",
        accentForeground: "#FFFFFF",
        background: "#FAFAF9",
        foreground: "#1C1917",
        muted: "#F5F5F4",
        mutedForeground: "#78716C",
        card: "#FFFFFF",
        cardForeground: "#1C1917",
        border: "#E7E5E4",
        ring: "#0D9488",
      },
    },
    {
      id: "dark",
      name: "Dark Mode",
      colors: {
        primary: "#22D3EE",
        primaryForeground: "#000000",
        secondary: "#164E63",
        secondaryForeground: "#CFFAFE",
        accent: "#34D399",
        accentForeground: "#000000",
        background: "#0C1222",
        foreground: "#F1F5F9",
        muted: "#1E293B",
        mutedForeground: "#94A3B8",
        card: "#162032",
        cardForeground: "#F1F5F9",
        border: "#2D4356",
        ring: "#22D3EE",
      },
    },
  ],
};

// Photography Theme
export const photographyTheme: DemoTheme = {
  demoId: "photography",
  name: "Photography",
  description: "Visual portfolio and galleries",
  defaultScheme: "minimal",
  schemes: [
    {
      id: "minimal",
      name: "Minimal Gallery",
      colors: {
        primary: "#000000",
        primaryForeground: "#FFFFFF",
        secondary: "#FAFAFA",
        secondaryForeground: "#000000",
        accent: "#DC2626",
        accentForeground: "#FFFFFF",
        background: "#FFFFFF",
        foreground: "#171717",
        muted: "#F5F5F5",
        mutedForeground: "#737373",
        card: "#FFFFFF",
        cardForeground: "#171717",
        border: "#E5E5E5",
        ring: "#000000",
      },
    },
    {
      id: "editorial",
      name: "Editorial",
      colors: {
        primary: "#1C1917",
        primaryForeground: "#FFFFFF",
        secondary: "#F5F5F4",
        secondaryForeground: "#1C1917",
        accent: "#B45309",
        accentForeground: "#FFFFFF",
        background: "#FAFAF9",
        foreground: "#1C1917",
        muted: "#E7E5E4",
        mutedForeground: "#78716C",
        card: "#FFFFFF",
        cardForeground: "#1C1917",
        border: "#D6D3D1",
        ring: "#1C1917",
      },
    },
    {
      id: "dark",
      name: "Dark Gallery",
      colors: {
        primary: "#FAFAFA",
        primaryForeground: "#171717",
        secondary: "#262626",
        secondaryForeground: "#FAFAFA",
        accent: "#F472B6",
        accentForeground: "#000000",
        background: "#0A0A0A",
        foreground: "#FAFAFA",
        muted: "#171717",
        mutedForeground: "#A3A3A3",
        card: "#171717",
        cardForeground: "#FAFAFA",
        border: "#262626",
        ring: "#FAFAFA",
      },
    },
  ],
};

// Export all themes
export const themes: Record<string, DemoTheme> = {
  restaurant: restaurantTheme,
  portfolio: portfolioTheme,
  saas: saasTheme,
  handyman: handymanTheme,
  ecommerce: ecommerceTheme,
  agency: agencyTheme,
  blog: blogTheme,
  "real-estate": realEstateTheme,
  gym: gymTheme,
  "law-firm": lawFirmTheme,
  medical: medicalTheme,
  photography: photographyTheme,
};

export * from "./types";
